stages:
  - build
  - release
  - qa
  - demo
  - production

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://localhost:2375"
  GIT_STRATEGY: fetch
  GET_SOURCES_ATTEMPTS: "3"
  IMAGE: $CI_REGISTRY_IMAGE/edge-pmacct

before_script:
  - ./build-all.sh
  - yum -y install docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build --pull -t $IMAGE .
  - docker tag $IMAGE $IMAGE:latest


build:
  stage: build
  image: centos:7
  except:
  - master
  - tags
  services:
  - docker:dind
  script:
  - docker push $IMAGE

release:
  stage: release
  image: centos:7
  only:
  - tags
  except:
  - master
  services:
  - docker:dind
  script:
  - docker tag $IMAGE $IMAGE:$CI_COMMIT_TAG
  - docker push $IMAGE