stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"
  GIT_STRATEGY: fetch
  GET_SOURCES_ATTEMPTS: "3"
  IMAGE: $CI_REGISTRY_IMAGE/edge-pmacct

before_script:
  - ./build-all.sh
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum -y install docker-ce
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $IMAGE:latest || true
  - docker build --cache-from $IMAGE:latest --pull -t $IMAGE:latest .

build:
  stage: build
  image: centos:7
  except:
  - master
  - tags
  services:
  - docker:dind
  script:
  - docker push $IMAGE

release:
  stage: release
  image: centos:7
  only:
  - tags
  except:
  - master
  services:
  - docker:dind
  script:
  - docker tag $IMAGE $IMAGE:$CI_COMMIT_TAG
  - docker push $IMAGE