stages:
  - build
  - release
  - qa
  - demo
  - production

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://localhost:2375"
  GIT_STRATEGY: fetch
  GET_SOURCES_ATTEMPTS: "3"

build:
  stage: build
  image: centos:7
  except:
  - master
  - tags
  services:
  - docker:dind
  script:
  - "./build-all.sh"
  - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
  - "docker build -t registry.gitlab.com/firescope/stratis/pmacct/edge-pmacct:latest ."
  - "docker push registry.gitlab.com/firescope/stratis/pmacct/edge-pmacct:latest"

release:
  stage: release
  image: centos:7
  only:
  - tags
  except:
  - master
  services:
  - docker:dind
  script:
  - "./build-all.sh"
  - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
  - "docker build -t registry.gitlab.com/firescope/stratis/pmacct/edge-pmacct:$CI_COMMIT_TAG ."
  - "docker tag registry.gitlab.com/firescope/stratis/pmacct/edge-pmacct:latest"
  - "docker push registry.gitlab.com/firescope/stratis/pmacct/edge-pmacct:$CI_COMMIT_TAG"
  - "docker push registry.gitlab.com/firescope/stratis/pmacct/edge-pmacct:latest"
